name: MarketPlace
version: '${project.version}'
main: cz.sengycraft.marketplace.MarketPlacePlugin
api-version: '1.20'
commands:
  sell:
    description: "Lists the item in players hand in the marketplace for sale"
    permission: marketplace.sell
  marketplacereload:
    description: "Reloads all configuration files"
    permission: marketplace.reload
  marketplace:
    description: "Displays a list of all items currently for sale in the marketplace"
    permission: marketplace.view

permissions:
  marketplace.sell:
    description: "Access to /sell command"
  marketplace.reload:
    description: "Access to /marketplacereload command"
  marketplace.view:
    description: "Access to /marketplace command"
